"""
page_email.py — Email Notification (P3 Feature).

Send generated trade confirmations via email using Python smtplib.
Supports Gmail SMTP (SSL) and generic SMTP servers.
Email config stored in data/email_config.json (admin-only setup).
"""

import streamlit as st
import json
import smtplib
import ssl
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path
from src.auth import log_audit

CONFIG_FILE = Path(__file__).parent.parent / "data" / "email_config.json"
POPULATED_DIR = Path(__file__).parent.parent / "data" / "populated"


def _load_config() -> dict:
    if CONFIG_FILE.exists():
        try:
            return json.loads(CONFIG_FILE.read_text())
        except Exception:
            pass
    return {}


def _save_config(cfg: dict):
    CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_FILE.write_text(json.dumps(cfg, indent=2))


def _send_email(cfg: dict, to_email: str, subject: str,
                body: str, attachment_path: Path = None) -> tuple[bool, str]:
    try:
        msg = MIMEMultipart()
        msg["From"]    = cfg["sender_email"]
        msg["To"]      = to_email
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "html"))

        if attachment_path and attachment_path.exists():
            with open(attachment_path, "rb") as f:
                part = MIMEBase("application", "octet-stream")
                part.set_payload(f.read())
            encoders.encode_base64(part)
            part.add_header(
                "Content-Disposition",
                f'attachment; filename="{attachment_path.name}"'
            )
            msg.attach(part)

        context = ssl.create_default_context()
        port = int(cfg.get("smtp_port", 465))

        if port == 465:
            with smtplib.SMTP_SSL(cfg["smtp_host"], port, context=context) as server:
                server.login(cfg["sender_email"], cfg["smtp_password"])
                server.sendmail(cfg["sender_email"], to_email, msg.as_string())
        else:
            with smtplib.SMTP(cfg["smtp_host"], port) as server:
                server.ehlo()
                server.starttls(context=context)
                server.login(cfg["sender_email"], cfg["smtp_password"])
                server.sendmail(cfg["sender_email"], to_email, msg.as_string())

        return True, "Email sent successfully."
    except Exception as e:
        return False, str(e)


def _email_body(filename: str, sender_name: str, trade_type: str = "") -> str:
    return f"""
    <div style="font-family:Arial,sans-serif;max-width:600px;margin:0 auto;">
        <div style="background:#060D1F;padding:24px;border-radius:12px 12px 0 0;text-align:center;">
            <div style="font-size:18px;font-weight:800;color:#00D4FF;">
                ⚡ TradeConfirmation AI
            </div>
            <div style="font-size:12px;color:rgba(255,255,255,0.4);margin-top:4px;">
                Capital Markets · Intelligent Document Automation
            </div>
        </div>
        <div style="background:#ffffff;padding:28px;">
            <p style="font-size:15px;font-weight:700;color:#1a1a1a;">
                Trade Confirmation Ready for Review
            </p>
            <p style="font-size:13px;color:#444;line-height:1.6;">
                Please find attached the trade confirmation document
                <strong>{filename}</strong>
                {f"for <strong>{trade_type}</strong>" if trade_type else ""},
                generated by TradeConfirmation AI.
            </p>
            <p style="font-size:13px;color:#444;line-height:1.6;">
                This document has passed all automated validation rules
                and is ready for your review and approval.
            </p>
            <div style="background:#f5f5f5;border-radius:8px;padding:14px;margin:16px 0;">
                <div style="font-size:12px;color:#888;">Sent by: {sender_name}</div>
                <div style="font-size:12px;color:#888;margin-top:4px;">
                    System: TradeConfirmation AI · Automated Generation Pipeline
                </div>
            </div>
            <p style="font-size:11px;color:#aaa;margin-top:20px;">
                This is an automated message. Please do not reply directly to this email.
            </p>
        </div>
        <div style="background:#f0f0f0;padding:12px;border-radius:0 0 12px 12px;
             text-align:center;font-size:10px;color:#aaa;">
            TradeConfirmation AI · Confidential
        </div>
    </div>
    """


def page_email():
    st.markdown(
        '<div class="page-header">'
        '<div class="page-title">Email <span>Notifications</span></div>'
        '<div class="page-subtitle">Send generated trade confirmations directly to counterparties via email</div>'
        '</div>',
        unsafe_allow_html=True
    )

    role     = st.session_state.get("role", "analyst")
    username = st.session_state.get("user", {}).get("username", "unknown")
    user     = st.session_state.get("user", {}) or {}
    is_admin = role == "admin"
    cfg      = _load_config()

    # ── SMTP Setup (admin only) ───────────────────────────────────────────
    with st.expander("⚙️ SMTP Configuration" + (" (Admin Only)" if not is_admin else ""),
                     expanded=not cfg):
        if not is_admin:
            st.markdown(
                '<div class="alert alert-warn">⚠ SMTP configuration requires Admin role.</div>',
                unsafe_allow_html=True
            )
        else:
            st.markdown(
                '<div style="font-size:12px;color:rgba(255,255,255,0.4);margin-bottom:12px;">'
                'Configure your SMTP server to enable email sending. '
                'For Gmail: use smtp.gmail.com, port 465, and an App Password.</div>',
                unsafe_allow_html=True
            )
            c1, c2 = st.columns(2)
            with c1:
                smtp_host  = st.text_input("SMTP Host",
                    value=cfg.get("smtp_host", "smtp.gmail.com"),
                    key="em_host")
                smtp_port  = st.selectbox("SMTP Port",
                    [465, 587], index=0 if cfg.get("smtp_port", 465) == 465 else 1,
                    key="em_port")
                sender_email = st.text_input("Sender Email",
                    value=cfg.get("sender_email", ""),
                    placeholder="yourapp@gmail.com",
                    key="em_email")
            with c2:
                smtp_password = st.text_input("App Password / SMTP Password",
                    value=cfg.get("smtp_password", ""),
                    type="password",
                    key="em_pass",
                    help="For Gmail: generate an App Password in Google Account Security settings")
                sender_name = st.text_input("Sender Display Name",
                    value=cfg.get("sender_name", "TradeConfirmation AI"),
                    key="em_name")

            col1, col2 = st.columns(2)
            with col1:
                if st.button("💾 Save SMTP Config", key="save_smtp",
                             use_container_width=True):
                    new_cfg = {
                        "smtp_host":    smtp_host,
                        "smtp_port":    smtp_port,
                        "sender_email": sender_email,
                        "smtp_password":smtp_password,
                        "sender_name":  sender_name,
                    }
                    _save_config(new_cfg)
                    cfg = new_cfg
                    log_audit(username, "ADMIN", "SMTP config updated")
                    st.success("✅ SMTP configuration saved.")

            with col2:
                test_addr = st.text_input("Test email address", key="em_test_addr",
                                          placeholder="test@example.com",
                                          label_visibility="collapsed")
                if st.button("📧 Send Test Email", key="test_smtp",
                             use_container_width=True):
                    if not cfg.get("smtp_host") or not cfg.get("sender_email"):
                        st.error("Save SMTP config first.")
                    elif not test_addr:
                        st.error("Enter a test email address.")
                    else:
                        ok, msg = _send_email(
                            cfg, test_addr,
                            "Test — TradeConfirmation AI",
                            "<p>SMTP configuration is working correctly.</p>"
                        )
                        if ok:
                            st.success(f"✅ Test email sent to {test_addr}")
                        else:
                            st.error(f"❌ {msg}")

    if not cfg.get("smtp_host"):
        st.markdown(
            '<div class="alert alert-info">💡 SMTP not configured. '
            'Ask an admin to set up the email configuration.</div>',
            unsafe_allow_html=True
        )
        return

    st.markdown('<div class="grad-divider"></div>', unsafe_allow_html=True)

    # ── Send confirmation email ───────────────────────────────────────────
    st.markdown(
        '<div style="font-size:14px;font-weight:700;color:#fff;margin-bottom:16px;">'
        '📨 Send Trade Confirmation</div>',
        unsafe_allow_html=True
    )

    # List generated documents
    doc_files = list(POPULATED_DIR.glob("*.docx")) if POPULATED_DIR.exists() else []
    if not doc_files:
        st.markdown(
            '<div class="alert alert-info">No generated documents found. '
            'Generate a template first.</div>',
            unsafe_allow_html=True
        )
        return

    doc_options = {f.name: f for f in sorted(doc_files, key=lambda x: x.stat().st_mtime,
                                               reverse=True)}

    c1, c2 = st.columns(2)
    with c1:
        selected_doc = st.selectbox("Document to Send",
                                    list(doc_options.keys()),
                                    key="em_doc")
        to_email = st.text_input("Recipient Email",
                                 placeholder="counterparty@bank.com",
                                 key="em_to")
    with c2:
        subject = st.text_input("Email Subject",
                                value=f"Trade Confirmation — {selected_doc}",
                                key="em_subject")
        trade_type_label = st.text_input("Trade Type (for email body)",
                                         placeholder="e.g. Interest Rate Swap",
                                         key="em_tt")

    # Preview
    with st.expander("👁 Preview Email Body"):
        sender_name = cfg.get("sender_name", "TradeConfirmation AI")
        preview_html = _email_body(selected_doc, sender_name, trade_type_label)
        st.markdown(
            f'<div style="background:#fff;border-radius:12px;padding:0;overflow:hidden;">'
            f'<iframe srcdoc="{preview_html.replace(chr(34), chr(39))}" '
            f'style="width:100%;height:400px;border:none;"></iframe></div>',
            unsafe_allow_html=True
        )

    st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)

    if st.button("📧 Send Confirmation Email", key="send_email",
                 use_container_width=True):
        if not to_email:
            st.markdown('<div class="alert alert-error">❌ Recipient email is required.</div>',
                        unsafe_allow_html=True)
        else:
            attachment = doc_options.get(selected_doc)
            sender_name = cfg.get("sender_name", "TradeConfirmation AI")
            body = _email_body(selected_doc, sender_name, trade_type_label)

            with st.spinner("Sending email…"):
                ok, msg = _send_email(cfg, to_email, subject, body, attachment)

            if ok:
                st.markdown(
                    f'<div class="alert alert-success">'
                    f'✅ Email sent to {to_email} with {selected_doc} attached.</div>',
                    unsafe_allow_html=True
                )
                log_audit(username, "GENERATE",
                          f"Email sent: {selected_doc} → {to_email}")
            else:
                st.markdown(
                    f'<div class="alert alert-error">❌ Failed to send: {msg}</div>',
                    unsafe_allow_html=True
                )

    # ── Email history ─────────────────────────────────────────────────────
    from src.auth import get_audit_logs
    email_logs = [l for l in get_audit_logs(200)
                  if l["action"] == "GENERATE" and "Email sent" in l.get("detail","")]

    if email_logs:
        st.markdown('<div class="grad-divider"></div>', unsafe_allow_html=True)
        st.markdown(
            '<div style="font-size:13px;font-weight:700;color:#fff;margin-bottom:12px;">'
            '📬 Email History</div>',
            unsafe_allow_html=True
        )
        rows = "".join(
            f'<tr>'
            f'<td style="color:rgba(255,255,255,0.35);font-size:11px;">{l["datetime"]}</td>'
            f'<td style="color:#00D4FF;font-size:12px;">{l["username"]}</td>'
            f'<td style="color:rgba(255,255,255,0.6);font-size:12px;">{l["detail"]}</td>'
            f'</tr>'
            for l in email_logs[:10]
        )
        st.markdown(
            '<div style="background:rgba(255,255,255,0.02);border:1px solid rgba(255,255,255,0.07);'
            'border-radius:12px;overflow:hidden;">'
            '<table class="tmpl-table" style="font-size:12px;">'
            '<thead><tr><th>Time</th><th>Sent By</th><th>Detail</th></tr></thead>'
            f'<tbody>{rows}</tbody></table></div>',
            unsafe_allow_html=True
        )
